name: DesiRNA Tests

on:
  push:
    branches: [main, refactoring]
  pull_request:
    branches: [main, refactoring]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: [3.7, 3.8, 3.9, 3.10, 3.11, 3.12]
          - os: ubuntu-20.04
            python-version: [3.7, 3.8, 3.9, 3.10, 3.11, 3.12]
          - os: macos-latest
            python-version: [3.11, 3.12]


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run tests
        run: |
          bash ./tests/test_DesiRNA.sh

      - name: Additional tests
        run: |
          bash ./tests/test_DesiRNA_errors.sh
