name: DesiRNA Tests

on:
  push:
    branches: [main, refactoring]
  pull_request:
    branches: [main, refactoring]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-latest]
        python-version: [3.7, 3.8, 3.9, "3.10", 3.11]
        exclude:
          - os: macos-latest
            python-version: 3.7
          - os: macos-latest
            python-version: 3.8
          - os: macos-latest
            python-version: 3.9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run tests
        run: |
          bash ./tests/test_DesiRNA.sh

      - name: Additional tests
        run: |
          bash ./tests/test_DesiRNA_errors.sh
