name: DesiRNA Tests

on:
  push:
    branches: [main, refactoring]
  pull_request:
    branches: [main, refactoring]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-latest]
        python-version: [3.7, 3.8, 3.9, 3.11]
        include:
          - os: ubuntu-22.04
            python-version: 3.7
            architecture: x64
          - os: ubuntu-22.04
            python-version: 3.8
            architecture: x64
          - os: ubuntu-22.04
            python-version: 3.9
            architecture: arm64
          - os: ubuntu-22.04
            python-version: 3.11
            architecture: arm64
          - os: ubuntu-20.04
            python-version: 3.7
            architecture: x64
          - os: ubuntu-20.04
            python-version: 3.8
            architecture: x64
          - os: ubuntu-20.04
            python-version: 3.9
            architecture: arm64
          - os: ubuntu-20.04
            python-version: 3.11
            architecture: arm64
          - os: macos-latest
            python-version: 3.7
            architecture: x64
          - os: macos-latest
            python-version: 3.8
            architecture: x64
          - os: macos-latest
            python-version: 3.9
            architecture: arm64
          - os: macos-latest
            python-version: 3.11
            architecture: arm64

    steps:
      - name: Increase Git Config core.longpaths
        if: runner.os == 'Windows'
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Run DesiRNA tests
        run: bash ./tests/test_DesiRNA.sh

      - name: Run DesiRNA error handling tests
        run: bash ./tests/test_DesiRNA_errors.sh

      - name: Set failed status if tests failed
        if: ${{ failure() }}
        run: exit 1
