name: DesiRNA Tests

on:
  push:
    branches: [main, refactoring]
  pull_request:
    branches: [main, refactoring]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-latest]
        python-version: [3.7, 3.8, 3.9, 3.11]

    steps:
      - name: Increase Git Config core.longpaths
        if: runner.os == 'Windows'
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install and configure gettext
        if: runner.os == 'macos'
        run: |
          brew install gettext
          brew link --force gettext
          sudo mkdir -p /usr/local/lib
          sudo ln -sf /usr/local/opt/gettext/lib/libintl.8.dylib /usr/local/lib/
          echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> $GITHUB_ENV
          echo 'export LDFLAGS="-L/usr/local/opt/gettext/lib"' >> $GITHUB_ENV
          echo 'export CPPFLAGS="-I/usr/local/opt/gettext/include"' >> $GITHUB_ENV
          echo 'export DYLD_LIBRARY_PATH="/usr/local/opt/gettext/lib:$DYLD_LIBRARY_PATH"' >> $GITHUB_ENV

      - name: Debug environment settings
        if: runner.os == 'macos'
        run: |
          echo "Checking DYLD_LIBRARY_PATH:"
          echo $DYLD_LIBRARY_PATH
          ls -l /usr/local/opt/gettext/lib/
          ls -l /usr/local/lib/libintl.8.dylib

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64  # Explicitly specify architecture if necessary


      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash
        
      - name: Run DesiRNA tests
        run: bash ./tests/test_DesiRNA.sh

      - name: Run DesiRNA error handling tests
        run: bash ./tests/test_DesiRNA_errors.sh
